language: cpp
compiler: clang
os: osx
script:
  - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && cmake --build .
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq eigen3
notifications:
  email: true
